Upgrade to pydantic-settings
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to
the `pydantic-settings` package.

See https://docs.pydantic.dev/2.7/migration/#basesettings-has-moved-to-pydantic-settings for more details.